# Code Generated by Sidekick is for learning and experimentation purposes only.
provider "aws" {
  region = "us-east-1"  # Change as needed
}

resource "aws_secretsmanager_secret" "example" {
  name        = "my_example_secret"
  description = "Secret for CI/CD pipelines"
}

resource "aws_secretsmanager_secret_version" "example" {
  secret_id     = aws_secretsmanager_secret.example.id
  secret_string = jsonencode({
    username = var.secret_username
    password = var.secret_password
  })
}
