# Code Generated by Sidekick is for learning and experimentation purposes only.
output "secret_arn" {
  value = aws_secretsmanager_secret.example.arn
  description = "The ARN of the secret stored in AWS Secrets Manager"
}
