# Code Generated by Sidekick is for learning and experimentation purposes only.
variable "secret_username" {
  description = "Username for the secret"
  type        = string
}

variable "secret_password" {
  description = "Password for the secret"
  type        = string
}
